services:
    app.menu:
        class: AppBundle\Menu\Builder
        arguments:
            - '@router'
            - '@translator'
            - '@security.authorization_checker'
            - '%symfonian_id.admin.translation_domain%'

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory:
            - '@app.menu'
            - mainMenu
        arguments:
            - '@knp_menu.factory'
            - []
        tags:
            - { name: knp_menu.menu, alias: app_main_menu }